// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdcoleacposdygmulurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkY29sZWFjcG9zZHlnbXVsdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDA1NDksImV4cCI6MjA2ODMxNjU0OX0.LUU5zrBNdE4IunIVfrwD6yBkqhrTgYbNwqrKLMkQ9A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});